[package]
name = "gpui-pre-util"
version = "0.3.6"
publish.workspace = true
edition.workspace = true
license = "Apache-2.0"

[lib]
name = "gpui_util"
doctest = false

[dependencies]
log.workspace = true
anyhow.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
which.workspace = true

[lints]
workspace = true
